# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1

ko:
  languageCode: ko
  contentDir: content/ko
  title: 한국어 웹사이트 제목...
  params:
    description: 한국어 사이트 설명...
  menu:
    main:
      - name: "홈"
        url: '/'
        weight: 1
      - name: "소개"
        url: '#about'
        weight: 2
