# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1

en-us:
  languageCode: en
  contentDir: content/en
  title: SuHyeon Yoo Portfolio
  params:
    description: This is English page.
  menu:
    main:
      - name: "home"
        url: '/'
        weight: 1
      - name: "about"
        url: '#about'
        weight: 2
